"""Set-2 gold drafts: NTSB aviation reports (ids 192719 to 192731). Written by a model (Claude)
from reading bench/set2/docs, after spec 0.2 was frozen. Not ground truth: a person checks every
fact."""

from __future__ import annotations

DRAFTS = {
    "ntsb-192719": {
        "pilot_age": ["28", "[[28]],Male"],
        "pilot_total_hours": ["4200", "[[4200 hours]] (Total, all aircraft)"],
        "pilot_make_model_hours": ["1100", "[[1100 hours]] (Total, this make and model)"],
        "pilot_last_90_days_hours": [None],
        "aircraft_year": ["1955", "Year of Manufacture: [[1955]]"],
        "airframe_total_hours": [None],
        "airport_elevation": [None],
        "runway_length": [None],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": ["4", "[[4 knots]] / None"],
        "temperature": ["18", "[[18°C]] / 13°C"],
        "altimeter_setting": ["30.02", "[[30.02 inches Hg]]"],
    },
    "ntsb-192720": {
        "pilot_age": ["39", "[[39]],Male"],
        "pilot_total_hours": ["2057", "[[2057 hours]] (Total, all aircraft)"],
        "pilot_make_model_hours": ["1204", "[[1204 hours]] (Total, this make and model)"],
        "pilot_last_90_days_hours": ["208", "[[208 hours]] (Last 90 days, all aircraft)"],
        "aircraft_year": ["2008", "R44 II [[2008]]"],
        "airframe_total_hours": ["1913.7", "[[1913.7 Hrs]]"],
        "airport_elevation": [None],
        "runway_length": [None],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": [None],
        "temperature": ["24", "[[24°C]] / 22°C"],
        "altimeter_setting": ["29.82", "[[29.82 inches Hg]]"],
    },
    "ntsb-192721": {
        "pilot_age": ["67", "[[67]],Male"],
        "pilot_total_hours": ["178", "(Estimated) [[178 hours]] (Total, all aircraft)"],
        "pilot_make_model_hours": ["30", "[[30 hours]] (Total, this make and model)"],
        "pilot_last_90_days_hours": ["23", "[[23 hours]] (Last 90 days, all aircraft)"],
        "aircraft_year": ["2009", "Year of Manufacture: [[2009]]"],
        "airframe_total_hours": ["240", "[[240 Hrs]] as of last inspection"],
        "airport_elevation": [None],
        "runway_length": [None],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": ["3", "[[3 knots]] / None"],
        "temperature": ["24", "[[24°C]] / 23°C"],
        "altimeter_setting": ["30.01", "[[30.01 inches Hg]]"],
    },
    "ntsb-192722": {
        "pilot_age": ["31", "[[31]],Male"],
        "pilot_total_hours": ["516", "[[516 hours]] (Total, all aircraft)"],
        "pilot_make_model_hours": ["148", "[[148 hours]] (Total, this make and model)"],
        "pilot_last_90_days_hours": ["116", "[[116 hours]] (Last 90 days, all aircraft)"],
        "aircraft_year": ["2001", "R44 [[2001]]"],
        "airframe_total_hours": [None],
        "airport_elevation": [None],
        "runway_length": [None],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": [None],
        "temperature": ["32", "[[32°C]] / 21°C"],
        "altimeter_setting": ["29.85", "[[29.85 inches Hg]]"],
    },
    # Instructional flight: the flight instructor (80) is the pilot in command, not the
    # private pilot (72, 1100 hours total, 20 hours in make and model).
    "ntsb-192723": {
        "pilot_age": ["80", "[[80]],Male"],
        "pilot_total_hours": ["8141", "[[8141 hours]] (Total, all aircraft)"],
        "pilot_make_model_hours": ["591", "[[591 hours]] (Total, this make and model)"],
        "pilot_last_90_days_hours": ["39", "[[39 hours]] (Last 90 days, all aircraft)"],
        "aircraft_year": ["1999", "M20R [[1999]]"],
        "airframe_total_hours": ["1509", "[[1509 Hrs]] as of last inspection"],
        "airport_elevation": ["682", "Airport Elevation: [[682 ft]] msl"],
        "runway_length": ["7400", "[[7400 ft]] / 150 ft"],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": [None],
        "temperature": ["27", "[[27°C]] / 22°C"],
        "altimeter_setting": ["30.18", "[[30.18 inches Hg]]"],
    },
    "ntsb-192724": {
        "pilot_age": ["52", "[[52]],Male"],
        "pilot_total_hours": ["153", "(Estimated) [[153 hours]] (Total, all aircraft)"],
        "pilot_make_model_hours": ["130", "[[130 hours]] (Total, this make and model)"],
        "pilot_last_90_days_hours": ["153", "[[153 hours]] (Last 90 days, all aircraft)"],
        "aircraft_year": ["1978", "Year of Manufacture: [[1978]]"],
        "airframe_total_hours": ["2625.7", "[[2625.7 Hrs]] as of last"],
        "airport_elevation": [None],
        "runway_length": [None],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": ["5", "[[5 knots]] / None"],
        "temperature": ["19", "[[19°C]] / 14°C"],
        "altimeter_setting": ["30.1", "[[30.1 inches Hg]]"],
    },
    "ntsb-192728": {
        "pilot_age": ["64", "[[64]],Male"],
        "pilot_total_hours": ["12865", "[[12865 hours]] (Total, all aircraft)"],
        "pilot_make_model_hours": ["6", "[[6 hours]] (Total, this make and model)"],
        "pilot_last_90_days_hours": ["7", "[[7 hours]] (Last 90 days, all aircraft)"],
        "aircraft_year": ["1978", "Year of Manufacture: [[1978]]"],
        "airframe_total_hours": ["1704", "[[1704 Hrs]] as of last"],
        "airport_elevation": ["2211", "Airport Elevation: [[2211 ft]] msl"],
        "runway_length": ["3200", "[[3200 ft]] / 60 ft"],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": ["9", "[[9 knots]] /"],
        "temperature": ["22", "[[22°C]] / 9°C"],
        "altimeter_setting": ["30.11", "[[30.11 inches Hg]]"],
    },
    "ntsb-192729": {
        "pilot_age": ["58", "[[58]],Male"],
        "pilot_total_hours": [None],
        "pilot_make_model_hours": [None],
        "pilot_last_90_days_hours": [None],
        "aircraft_year": ["1985", "2150A [[1985]]"],
        "airframe_total_hours": [None],
        "airport_elevation": [None],
        "runway_length": [None],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": ["9", "[[9 knots]] / None"],
        "temperature": ["31", "[[31°C]] / 23°C"],
        "altimeter_setting": ["29.94", "[[29.94 inches Hg]]"],
    },
    "ntsb-192730": {
        "pilot_age": ["34", "[[34]],Male"],
        "pilot_total_hours": ["109", "[[109 hours]] (Total, all aircraft)"],
        "pilot_make_model_hours": ["4", "[[4 hours]] (Total, this make and model)"],
        "pilot_last_90_days_hours": ["10", "[[10 hours]] (Last 90 days, all aircraft)"],
        "aircraft_year": ["1969", "177 B [[1969]]"],
        "airframe_total_hours": ["5200.48", "[[5200.48 Hrs]] at time of"],
        "airport_elevation": [None],
        "runway_length": [None],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": ["3", "[[3 knots]] / None"],
        "temperature": ["30", "[[30°C]] / 23°C"],
        "altimeter_setting": ["30", "[[30 inches Hg]]"],
    },
    "ntsb-192731": {
        "pilot_age": ["65", "[[65]],Male"],
        "pilot_total_hours": ["1000", "[[1000 hours]] (Total, all aircraft)"],
        "pilot_make_model_hours": ["150", "[[150 hours]] (Total, this make and model)"],
        "pilot_last_90_days_hours": [None],
        "aircraft_year": ["2015", "Year of Manufacture: [[2015]]"],
        "airframe_total_hours": [None],
        "airport_elevation": [None],
        "runway_length": [None],
        "visibility": ["10", "Visibility [[10 miles]]"],
        "wind_speed": ["5", "[[5 knots]] / None"],
        "temperature": ["31", "[[31°C]] / 25°C"],
        "altimeter_setting": ["29.95", "[[29.95 inches Hg]]"],
    },
}
