"""The field question of #67 on a second document kind: can a typed-decision model find a number
that spec 0.3 admits as the wrong field in an NTSB aviation report? This is the field judge
(bench/judges/fields/judge.py) with the aviation set as its gold. The plan is on #67.

    uv run python bench/judges/aviation/judge.py split    # split.json, before any model run
    TYPESAFE_API_KEY=... uv run python bench/judges/aviation/judge.py run jev
    uv run python bench/judges/aviation/judge.py report   # REPORT.md, report.json
    uv run python bench/judges/aviation/judge.py report --check

The question is the field judge's, with the report in place of the drug label. It was written
once, before the first run, and is not tuned on these numbers.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

HERE = Path(__file__).parent
BENCH = HERE.parent.parent
sys.path[:0] = [str(HERE.parent / "keys"), str(BENCH / "aviation")]

import judge as kj  # noqa: E402  (bench/judges/keys/judge.py)
from aviation import FIELDS, UNIT_AFTER  # noqa: E402  (bench/aviation/aviation.py)

_spec = importlib.util.spec_from_file_location("fields_judge", HERE.parent / "fields" / "judge.py")
assert _spec and _spec.loader
fj = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(fj)

UNITS = json.loads((BENCH / "set2" / "gold" / "ntsb-192719.json").read_text())["units"]


def candidate(text: str, span: list[int], field: str) -> dict[str, Any]:
    """The number as an extraction of the field: the number, in the field's unit, with the
    number and its unit suffix as evidence, in UTF-8 bytes."""
    a, b = span
    m = UNIT_AFTER.match(text, b)
    if m is None:
        raise SystemExit(f"no unit after the number at {a}")

    def byte(i: int) -> int:
        return len(text[:i].encode())

    return {
        "field": field,
        "value": text[a:b],
        "unit": FIELDS[field]["schema"]["unit"],
        "evidence": {"start": byte(a), "end": byte(m.end())},
    }


def admitted(text: str, span: list[int]) -> list[str]:
    """The fields that spec 0.3 admits the number as, each decided alone."""
    from groundgate import admit

    out = []
    for f, d in FIELDS.items():
        schema = {"fields": {f: d["schema"]}, "units": UNITS}
        (decision,) = admit(text, schema, [candidate(text, span, f)]).decisions
        if decision.outcome == "admitted":
            out.append(f)
    return out


def gold() -> list[dict[str, Any]]:
    """Each labeled number of the aviation set at which spec 0.3 admits one field or more, with
    its label and those fields. Numbers labeled not sure are left out."""
    labels = json.loads((BENCH / "aviation" / "labels.json").read_text())
    texts: dict[str, str] = {}
    out = []
    for it in json.loads((BENCH / "aviation" / "items.json").read_text()):
        if labels[it["id"]] is None:
            continue
        if it["doc"] not in texts:
            path = BENCH / "aviation" / "docs" / f"{it['doc']}.txt"
            texts[it["doc"]] = path.read_text(encoding="utf-8")
        fields = admitted(texts[it["doc"]], it["span"])
        if fields:
            out.append(
                {
                    "id": it["id"],
                    "set": "aviation",
                    "doc": it["doc"],
                    "span": it["span"],
                    "label": labels[it["id"]],
                    "spec_0.3": fields,
                }
            )
    return out


def question(fields: list[str]) -> dict[str, Any]:
    return {
        f: {
            "type": "noul",
            "instructions": (
                "The text is from an NTSB aviation accident report and marks one number in "
                "brackets. Does the report state that number as this value? "
                + FIELDS[f]["description"]
            ),
        }
        for f in fields
    }


def prompt(it: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    return kj.state(it), question(it["spec_0.3"])


def main() -> None:
    # the key judge runs and splits, and the field judge scores and reports, with this gold
    kj.HERE, kj.gold, kj.prompt, kj.keep, kj.ENGINES = HERE, gold, prompt, fj.keep, fj.ENGINES
    fj.HERE, fj.gold = HERE, gold
    fj.ITEMS, fj.DOCS = "Numbers", "Reports"
    fj.TITLE = "# Finding wrong fields in NTSB reports with a typed-decision model"
    fj.INTRO = (
        "Generated by `bench/judges/aviation/judge.py report` from `split.json` and the "
        "`answers-*.json` files. The plan is on #67. The gold is the labeled numbers of the "
        "aviation set at which spec 0.3 admits a field, split by report into a calibration part "
        "and a test part. A pair is a number and a field that spec 0.3 admits it as. It is right "
        "when the label holds the field, and wrong when it does not."
    )
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("split")
    p = sub.add_parser("run")
    p.add_argument("engine", choices=sorted(fj.ENGINES))
    p = sub.add_parser("report")
    p.add_argument("--check", action="store_true", help="fail if the committed files differ")
    args = ap.parse_args()
    if args.cmd == "split":
        kj.split()
    elif args.cmd == "run":
        kj.run(args.engine)
    else:
        fj.report(args.check)


if __name__ == "__main__":
    main()
