"""How often spec 0.3 flags NON_VERBATIM_EVIDENCE in the recorded extraction runs of the v0.1
set and set 2, and how each flagged quote differs from its span. This decides whether the quote
question of #67 has enough natural flags to label and ask a model.

    uv run --group langextract python bench/judges/quotes/count.py   # COUNTS.md, counts.json
    uv run --group langextract python bench/judges/quotes/count.py --check

It prints no document text and asks no model.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

HERE = Path(__file__).parent
BENCH = HERE.parent.parent
sys.path[:0] = [str(BENCH), str(HERE.parent / "keys")]

import judge as kj  # noqa: E402  (bench/judges/keys/judge.py)
import score  # noqa: E402  (bench/score.py)

import groundgate as gg  # noqa: E402
from groundgate.text import _HYPHEN_BREAK, normalize_ws, verbatim_equal  # noqa: E402

SETS = {"v0.1": BENCH, "set 2": BENCH / "set2"}


def difference(quote: str, span: str) -> str:
    """How the quote differs from the span text, after the §4.4 normalisation for the verbatim
    comparison."""
    q, s = (normalize_ws(_HYPHEN_BREAK.sub("", x)) for x in (quote, span))
    if q.lower() == s.lower():
        return "case only"
    if s in q:
        return "the quote adds text"
    if q in s:
        return "the quote drops text"
    return "the quote changes text"


def count(path: Path) -> dict[str, Any]:
    score.SET = path
    golds = score.load_gold(False)
    score.SET2 = any(g.groups for g in golds.values())
    runs, _ = score.load_runs(golds)
    candidates, flags = 0, 0
    pairs: dict[tuple[str, int, int, str], str] = {}
    kinds: Counter[str] = Counter()
    for docs in runs.values():
        for doc, cands in docs.items():
            g = golds[doc]
            if g.control:
                continue
            by = {d.candidate_sha256: d for d in gg.admit(g.text, g.schema, cands).decisions}
            raw = g.text.encode()
            for c in cands:
                candidates += 1
                d = by[gg.digest("candidate", c)]
                if "NON_VERBATIM_EVIDENCE" not in d.codes or d.evidence is None:
                    continue
                flags += 1
                kinds[g.kind] += 1
                a, b = d.evidence
                span = raw[a:b].decode()
                ev = c["evidence"]  # the value item: one object, or first in a list
                quote = (ev[0] if isinstance(ev, list) else ev)["text"]
                assert not verbatim_equal(quote, span)
                pairs[(doc, a, b, quote)] = difference(quote, span)
    return {
        "candidates": candidates,
        "flags": flags,
        "flags_by_kind": dict(sorted(kinds.items())),
        "pairs": len(pairs),
        "pairs_by_difference": dict(sorted(Counter(pairs.values()).items())),
    }


CLASSES = ("case only", "the quote adds text", "the quote drops text", "the quote changes text")
CEILINGS = (0.05, 0.1, 0.2)


def clears_needed(ceiling: float) -> int:
    """The fewest right clears, with no escape, whose 95% upper bound is below the ceiling."""
    return next(n for n in range(1, 1000) if kj.upper_95(0, n) < ceiling)


def markdown(counts: dict[str, dict[str, Any]]) -> str:
    md = [
        "# Quote flags in the recorded runs",
        "",
        "Generated by `bench/judges/quotes/count.py` from the recorded runs of the v0.1 set and "
        "set 2. [README.md](README.md) says what it counts.",
        "",
        "| Set | Candidates | Quote flags | Different pairs |",
        "|---|---:|---:|---:|",
    ]
    md += [f"| {n} | {c['candidates']} | {c['flags']} | {c['pairs']} |" for n, c in counts.items()]
    md += ["", "| How the quote differs | " + " | ".join(counts) + " |"]
    md += ["|---|" + "---:|" * len(counts)]
    for cls in CLASSES:
        row = [str(c["pairs_by_difference"].get(cls, 0)) for c in counts.values()]
        md.append(f"| {cls[0].upper() + cls[1:]} | " + " | ".join(row) + " |")
    md += [
        "",
        "Right clears that a threshold needs on the calibration part with no escape, from the "
        "one-sided 95% upper bound of the key judge, against the different pairs of both sets:",
        "",
        "| Ceiling | Right clears needed | Different pairs in both sets |",
        "|---:|---:|---:|",
    ]
    pairs = sum(c["pairs"] for c in counts.values())
    md += [f"| {c} | {clears_needed(c)} | {pairs} |" for c in CEILINGS]
    return "\n".join(md) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed files differ")
    args = ap.parse_args()
    counts = {name: count(path) for name, path in SETS.items()}
    out = {
        HERE / "counts.json": json.dumps(counts, indent=2) + "\n",
        HERE / "COUNTS.md": markdown(counts),
    }
    if args.check:
        stale = [p.name for p, body in out.items() if not p.exists() or p.read_text() != body]
        if stale:
            raise SystemExit(f"out of date: {', '.join(stale)}; run count.py")
        print("COUNTS.md is up to date")
        return
    for path, body in out.items():
        path.write_text(body)
    print("wrote COUNTS.md, counts.json")


if __name__ == "__main__":
    main()
